### PR TITLE
Feature/setup pipeline for backend doc generation

### PR DESCRIPTION
**Pull request by kouamschekina**
- Created a pipeline that generates a documentation for the backend.
- Created the `documentation.adoc` file to be able to setup the pipeline

### CODE REVIEW

**Review by stephane-segning — CHANGES_REQUESTED** [review]
This would work. But do you know that asciidoc has a plugin for spring boot? That you can just use to generate a spring boot config? Please use that

**Comment by stephane-segning** [comment]
You'll want to generate the spring boot doc, then import it to your own doc, then generate a pdf from your doc

**Comment by kouamschekina** [comment]
Hello sir @stephane-segning . Thanks for the review.  Please is the location of the `documentation.adoc` file okay or it will be better in a docs folder?

**Comment by kouamschekina** [comment]
Hello sir @stephane-segning . I encounter an issue at the level of converting the `.adoc` files to pdf. Each time i used the `asciidocj` for the pdf to be generated, i encountered an error.

**Comment by stephane-segning** [comment]
I see, this is strange. But it's ok, just ensure the asci is generated and as you proposed, inside the docs/ folder. Let's look into the pdf generation error next. Can you post it here btw?

**Comment by kouamschekina** [comment]
Hello sir @stephane-segning  This is the error i encountered
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/kouam/Desktop/GIS_projects/lynx-scanner/lynx-scanner-backend/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating root project 'lynx-backend'.
> Could not get unknown property 'inputs' for extension 'asciidoctorj' of type org.asciidoctor.gradle.jvm.AsciidoctorJExtension_Decorated.
```
This is what i implemented
```
asciidoctorj {
    inputs.fileTree(dir: 'docs', include: ['**/*.adoc']) 
    outputs.dir file('build/pdf') 
}
```

**Pull request closed without merging**
