### PR TITLE
Integration test for REST endpoint

### PR DESCRIPTION
**Pull request by Ogenbertrand**

### CODE REVIEW

**Comment by Ogenbertrand** [comment]
@stephane-segning 
Wrote an integration test to the test REST endpoint of the Lynx scanner backend application.

[Add intergration test for REST endpoint](https://github.com/stephane-segning/lynx-scanner-
backend/pull/23/commits/0f442e1c9e94542c09d719be1dd9bf55ed6a7bf7)

**Comment by Ogenbertrand** [comment]
@stephane-segning 
Wrote an integration test to test the REST endpoint of the Lynx scanner backend application.

[Add intergration test for REST endpoint](https://github.com/stephane-segning/lynx-scanner-backend/pull/23/commits/0f442e1c9e94542c09d719be1dd9bf55ed6a7bf7)

**Review by Koufan-De-King — APPROVED** [review]

**Review by stephane-segning — CHANGES_REQUESTED** [review]
Who asked you to work on a ticket which is in backlog?

**Comment by Ogenbertrand** [comment]
> Who asked you to work on a ticket which is in backlog?

@stephane-segning 
Sir i had no idea it was in the backlog. i took it cuz it was among the last ticket i worked on that's setting up github action workflow in the spring boot action.

**Pull request closed without merging**
