### PR TITLE
feat(backend): Set up basic keycloak using docker

### PR DESCRIPTION
**Pull request by Ngha-Boris**

### CODE REVIEW

**Review by ValantineSuh — APPROVED** [review]
Looks Good!

**Review by stephane-segning — CHANGES_REQUESTED** [review]
Write a small guide please on how to kickoff this keycloak into a file keycloak.md inside of docs/

**Comment by Ngha-Boris** [comment]
> Write a small guide please on how to kickoff this keycloak into a file keycloak.md inside of docs/

Ok sir

**Review by bryandino673 — APPROVED** [review]

**Comment by Ngha-Boris** [comment]
> > Write a small guide please on how to kickoff this keycloak into a file keycloak.md inside of docs/
> 
> Ok sir

Done

**Review by stephane-segning — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
